@startuml

!include ./C4/C4_Container.puml

SHOW_PERSON_OUTLINE()

Person(customer, "Personal Banking Customer", "A customer of the bank, with personal bank accounts")

System_Boundary(boundary, "Internet Banking System") {

        Container(webapp, "Web Application", "Clojure & Integrant", "Delivers static content and the internet banking single page application")
        Container(spa, "Single Page Application", "ClojureScript & re-frame", "Provides internet banking functionality to customers via their web browser")
        Container(mobile, "Mobile App", "ClojureScript & Expo", "Provides limited internet banking functionality to customers via their mobile device")
        Container(api, "API Application", "Clojure & reitit", "Provides internet banking functionality via JSON/HTTPS API")
        ContainerDb(db, "Database", "XTDB", "Stores banking transactions in a bitemporal time machine")

}

System_Ext(email, "Email system", "The internal mail server")
System_Ext(mainframe, "Mainframe Banking System", "Processes all core banking rules")

Rel(customer, webapp, "Visits bigbank.com/ib", HTTPS)
Rel(customer, spa, "Views account balances, and makes payments using")
Rel(customer, mobile, "Views account balances, and makes payments using")
Rel(email, customer, "Sends emails to")
Rel(webapp, spa, "Delivers to the customer's web browser")
Rel(spa, api, "Makes API calls to", "JSON/HTTPS")
Rel(mobile, api, "Makes API calls to", "JSON/HTTPS")
Rel(api, db, "Reads from & writes to", "xtdb.api")
Rel(api, email, "Sends email using", "SMTP")
Rel(api, mainframe, "Makes API calls to", "XML/HTTPS")

@enduml
